// Figma Design System Typography
export const typography = {
  fontFamily: [
    'Noto Kufi Arabic',
    'Helvetica',
    'Arial',
    'sans-serif',
  ].join(','),
  
  // Standard MUI typography variants with Figma values
  h1: {
    fontFamily: 'Alexandria, Helvetica, Arial, sans-serif',
    fontWeight: 300,
    fontSize: 96,
    lineHeight: 1.167,
    letterSpacing: '-0.0156em',
  },
  h2: {
    fontFamily: 'Alexandria, Helvetica, Arial, sans-serif',
    fontWeight: 300,
    fontSize: 60,
    lineHeight: 1.2,
    letterSpacing: '-0.0083em',
  },
  h3: {
    fontFamily: 'Alexandria, Helvetica, Arial, sans-serif',
    fontWeight: 400,
    fontSize: 48,
    lineHeight: 1.167,
    letterSpacing: '0em',
  },
  h4: {
    fontFamily: 'Alexandria, Helvetica, Arial, sans-serif',
    fontWeight: 600,
    fontSize: 34,
    lineHeight: 1.235,
    letterSpacing: '0.0074em',
  },
  h5: {
    fontFamily: 'Alexandria, Helvetica, Arial, sans-serif',
    fontWeight: 700,
    fontSize: 24,
    lineHeight: 1.4,
    letterSpacing: '0em',
  },
  h6: {
    fontFamily: 'Alexandria, Helvetica, Arial, sans-serif',
    fontWeight: 500,
    fontSize: 20,
    lineHeight: 1.6,
    letterSpacing: '0.0075em',
  },
  subtitle1: {
    fontFamily: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
    fontWeight: 600,
    fontSize: 16,
    lineHeight: 1.75,
    letterSpacing: '0.0094em',
  },
  subtitle2: {
    fontFamily: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: 1.57,
    letterSpacing: '0.0071em',
  },
  body1: {
    fontFamily: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
    fontSize: 16,
    fontWeight: 400,
    lineHeight: 1.75,
    letterSpacing: '0.0063em',
  },
  body2: {
    fontFamily: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 1.7,
    letterSpacing: '0.0071em',
  },
  button: {
    fontFamily: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
    fontWeight: 500,
    fontSize: 14,
    lineHeight: 1.714,
    letterSpacing: '0em',
    textTransform: 'none' as const,
  },
  caption: {
    fontFamily: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
    fontSize: 12,
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: '0.0083em',
  },
  overline: {
    fontFamily: 'Noto Kufi Arabic, Helvetica, Arial, sans-serif',
    fontSize: 12,
    fontWeight: 400,
    lineHeight: 2.66,
    letterSpacing: '0.0833em',
    textTransform: 'uppercase' as const,
  },
};